# Generated by Django 6.0.4 on 2026-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('jerseyNo', models.IntegerField()),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('skillSet', models.CharField(max_length=50)),
                ('bowlingType', models.CharField(blank=True, max_length=50, null=True)),
                ('battingStyle', models.CharField(max_length=50)),
                ('runsScored', models.IntegerField()),
                ('average', models.FloatField()),
                ('strikeRate', models.FloatField()),
                ('wickets', models.IntegerField(blank=True, null=True)),
                ('economy', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
